#!/usr/bin/env python3
import subprocess
import re
import time
import os
import json

CONFIG_FILE = os.path.expanduser("~/.config/niri/cfg/display.kdl")
CACHE_FILE = os.path.expanduser("~/.config/niri/cfg/display_cache.json")
WALLPAPER_SCRIPT = os.path.expanduser("~/.config/niri/launch-wallpaper.sh")

WALLPAPERS = {
    "HP Inc. OMEN 34c CNC3492SD6": "3373381434",
    "PNP(XXX) AAA Unknown": "1979650342",
    "PNP(AOC) U2879G6 0x00000426": "2940771066",
    "Samsung Electric Company SAMSUNG 0x01000E00": "2183937834"
}

def load_cache():
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, 'r') as f:
                return json.load(f)
        except:
            pass
    return {}

def save_cache(cache):
    with open(CACHE_FILE, 'w') as f:
        json.dump(cache, f, indent=4)

def get_outputs():
    result = subprocess.run(["niri", "msg", "outputs"], capture_output=True, text=True)
    outputs = {}
    current_output = {}
    
    for line in result.stdout.splitlines():
        if line.startswith("Output "):
            if current_output and 'name' in current_output:
                outputs[current_output['name']] = current_output
            current_output = {}
            m = re.match(r'Output "(.+?)" \((.+?)\)', line)
            if m:
                current_output['name'] = m.group(1)
                current_output['port'] = m.group(2)
        elif line.strip().startswith("Current mode:"):
            m = re.search(r'Current mode: ([0-9]+x[0-9]+) @ ([0-9.]+)', line)
            if m:
                current_output['mode'] = f"{m.group(1)}@{m.group(2)}"
        elif line.strip().startswith("Variable refresh rate:"):
            if "enabled" in line:
                current_output['vrr'] = True
        elif line.strip().startswith("Logical position:"):
            m = re.search(r'Logical position: ([0-9]+), ([0-9]+)', line)
            if m:
                current_output['pos_x'] = m.group(1)
                current_output['pos_y'] = m.group(2)
        elif line.strip().startswith("Scale:"):
            m = re.search(r'Scale: ([0-9.]+)', line)
            if m:
                scale_val = m.group(1)
                if scale_val.endswith('.0'):
                    scale_val = scale_val[:-2]
                current_output['scale'] = scale_val
        elif line.strip().startswith("Transform:"):
            val = line.split(":", 1)[1].strip()
            if "90°" in val:
                current_output['transform'] = "90"
            elif "180°" in val:
                current_output['transform'] = "180"
            elif "270°" in val:
                current_output['transform'] = "270"
            elif "normal" in val:
                current_output['transform'] = "normal"
            else:
                current_output['transform'] = "normal"
                
    if current_output and 'name' in current_output:
        outputs[current_output['name']] = current_output
        
    return outputs

def generate_kdl(all_outputs):
    lines = ["// ────────────── Output Configuration ──────────────", 
             "// Auto-generated by niri-wdisplays-sync", ""]
    # Sort names so KDL remains stable
    for name in sorted(all_outputs.keys()):
        out = all_outputs[name]
        lines.append(f'output "{name}" {{')
        if 'mode' in out:
            lines.append(f'    mode "{out["mode"]}"')
        if 'scale' in out:
            lines.append(f'    scale {out["scale"]}')
        if 'transform' in out:
            lines.append(f'    transform "{out["transform"]}"')
        if 'pos_x' in out and 'pos_y' in out:
            lines.append(f'    position x={out["pos_x"]} y={out["pos_y"]}')
        if out.get('vrr'):
            lines.append(f'    variable-refresh-rate')
        lines.append('}')
        lines.append('')
    return "\n".join(lines)

def generate_wallpaper_script(active_outputs):
    args = ["/home/deggio/Projects/linux-wallpaperengine/build/output/linux-wallpaperengine", 
            "--layer", "background", "--disable-particles"]
    for name, out in active_outputs.items():
        if name in WALLPAPERS and 'port' in out:
            args.extend(["--screen-root", out['port'], "--bg", WALLPAPERS[name]])
            
    script_content = f"#!/bin/bash\nexec {' '.join(args)}\n"
    with open(WALLPAPER_SCRIPT, 'w') as f:
        f.write(script_content)
    os.chmod(WALLPAPER_SCRIPT, 0o755)

def main():
    last_kdl = ""
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            last_kdl = f.read()

    cache = load_cache()
    last_active_names = set()
    print("Starting smart synchronization niri <-> wdisplays...")
    
    while True:
        try:
            active_outputs = get_outputs()
            if not active_outputs:
                time.sleep(3)
                continue
            
            current_active_names = set(active_outputs.keys())
            layout_changed = False
            
            # If a screen is connected or disconnected, force an update
            if current_active_names != last_active_names:
                layout_changed = True
                last_active_names = current_active_names

            # Identify if any internal configuration has changed
            for name, out in active_outputs.items():
                if name not in cache or cache[name] != out:
                    cache[name] = out
                    layout_changed = True
            
            save_cache(cache)
            new_kdl = generate_kdl(cache)
            
            if new_kdl.strip() != last_kdl.strip() or layout_changed:
                with open(CONFIG_FILE, 'w') as f:
                    f.write(new_kdl)
                last_kdl = new_kdl
                print("Layout or port configuration changed! Updating and restarting...", CONFIG_FILE)
                
                # Regenerate wallpaper script with current ports (DP-1, etc)
                generate_wallpaper_script(active_outputs)
                
                # Restart wallpaper service
                subprocess.run(["systemctl", "--user", "restart", "linux-wallpaperengine.service"])
                
        except Exception as e:
            print("Error:", e)
        
        time.sleep(3)

if __name__ == "__main__":
    main()
